version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: "develop"
    labels:
      - dependabot
      - actions
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    target-branch: "develop"
    labels:
      - dependabot
      - npm
    schedule:
      interval: daily
